config/routes.rb
Rails.application.routes.draw do
  resources :vendedor_clientes
  resources :vendedors
  resources :alquilers
  resources :clientes
  resources :peliculas
  devise_for :usuarios
  get 'inicio/index'
  root 'inicio#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Presta Pelis </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><a href="<%= peliculas_path %>">Peliculas</a></li>
        <% if usuario_signed_in? %>
          <li><a href="<%= alquilers_path %>">Alquilers</a></li>
          <li><a href="<%= clientes_path %>">Clientes</a></li>
            <li><a href="<%= vendedors_path %>">Vendedors</a></li>
              <li><a href="<%= vendedor_clientes_path %>">Vendedor_clientes</a></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if usuario_signed_in? %>
        <li><a> <%= current_usuario.email %> </a></li>
        	<li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
        	<li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Session</a></li>
        <% else %>
        	<li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
        	<li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>