config/routes.rb
Rails.application.routes.draw do
  resources :vendedor_clientes
  resources :vendedors
  resources :alquilers
  resources :clientes
  resources :peliculas
  devise_for :usuarios
  get 'inicio/index'
  root 'inicio#index'
end

app/models/alquiler.rb
class Alquiler < ActiveRecord::Base
  belongs_to :pelicula
  belongs_to :cliente
end

app/controllers/alquilers_controller.rb
class AlquilersController < ApplicationController
  before_action :set_alquiler, only: [:show, :edit, :update, :destroy]

  # GET /alquilers
  # GET /alquilers.json
  def index
    @alquilers = Alquiler.all
  end

  # GET /alquilers/1
  # GET /alquilers/1.json
  def show
  end

  # GET /alquilers/new
  def new
    @alquiler = Alquiler.new
  end

  # GET /alquilers/1/edit
  def edit
  end

  # POST /alquilers
  # POST /alquilers.json
  def create
    @alquiler = Alquiler.new(alquiler_params)

    respond_to do |format|
      if @alquiler.save
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully created.' }
        format.json { render :show, status: :created, location: @alquiler }
      else
        format.html { render :new }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alquilers/1
  # PATCH/PUT /alquilers/1.json
  def update
    respond_to do |format|
      if @alquiler.update(alquiler_params)
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully updated.' }
        format.json { render :show, status: :ok, location: @alquiler }
      else
        format.html { render :edit }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alquilers/1
  # DELETE /alquilers/1.json
  def destroy
    @alquiler.destroy
    respond_to do |format|
      format.html { redirect_to alquilers_url, notice: 'Alquiler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alquiler
      @alquiler = Alquiler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alquiler_params
      params.require(:alquiler).permit(:num_alquiler, :fecha_out, :fecha_in, :pelicula_id, :cliente_id)
    end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/views/alquilers/_form.html.erb
<%= form_for(@alquiler) do |f| %>
  <% if @alquiler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alquiler.errors.count, "error") %> prohibited this alquiler from being saved:</h2>

      <ul>
      <% @alquiler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num_alquiler %><br>
    <%= f.number_field :num_alquiler %>
  </div>
  <div class="field">
    <%= f.label :fecha_out %><br>
    <%= f.date_select :fecha_out %>
  </div>
  <div class="field">
    <%= f.label :fecha_in %><br>
    <%= f.date_select :fecha_in %>
  </div>
  <div class="field">
    <%= f.label :pelicula_id %><br>
   <%= f.select("pelicula_id",Pelicula.all.collect {|l| [l.titulo, l.id ] }, { include_blank: 'Seleccione Pelicula'}) %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br>
   <%= f.select("cliente_id",Cliente.all.collect {|l| [l.nombre, l.id ] }, { include_blank: 'Seleccione Cliente'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alquilers/edit.html.erb
<h1>Editing Alquiler</h1>

<%= render 'form' %>

<%= link_to 'Show', @alquiler %> |
<%= link_to 'Back', alquilers_path %>

app/views/alquilers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alquilers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Num alquiler</th>
      <th>Fecha out</th>
      <th>Fecha in</th>
      <th>Pelicula</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alquilers.each do |alquiler| %>
      <tr>
        <td><%= alquiler.num_alquiler %></td>
        <td><%= alquiler.fecha_out %></td>
        <td><%= alquiler.fecha_in %></td>
        <td><%= alquiler.pelicula.titulo %></td>
        <td><%= alquiler.cliente.nombre %></td>
        <td><%= link_to 'Show', alquiler %></td>
        <td><%= link_to 'Edit', edit_alquiler_path(alquiler) %></td>
        <td><%= link_to 'Destroy', alquiler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alquiler', new_alquiler_path %>

app/views/alquilers/new.html.erb
<h1>New Alquiler</h1>

<%= render 'form' %>

<%= link_to 'Back', alquilers_path %>

app/views/alquilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num alquiler:</strong>
  <%= @alquiler.num_alquiler %>
</p>

<p>
  <strong>Fecha out:</strong>
  <%= @alquiler.fecha_out %>
</p>

<p>
  <strong>Fecha in:</strong>
  <%= @alquiler.fecha_in %>
</p>

<p>
  <strong>Pelicula:</strong>
  <%= @alquiler.pelicula.titulo %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @alquiler.cliente.nombre %>
</p>

<%= link_to 'Edit', edit_alquiler_path(@alquiler) %> |
<%= link_to 'Back', alquilers_path %>