config/routes.rb
Rails.application.routes.draw do
  resources :vendedor_clientes
  resources :vendedors
  resources :alquilers
  resources :clientes
  resources :peliculas
  devise_for :usuarios
  get 'inicio/index'
  root 'inicio#index'
end

app/models/pelicula.rb
class Pelicula < ActiveRecord::Base
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  before_action :set_pelicula, only: [:show, :edit, :update, :destroy]

  # GET /peliculas
  # GET /peliculas.json
  def index
    @peliculas = Pelicula.all
  end

  # GET /peliculas/1
  # GET /peliculas/1.json
  def show
  end

  # GET /peliculas/new
  def new
    @pelicula = Pelicula.new
  end

  # GET /peliculas/1/edit
  def edit
  end

  # POST /peliculas
  # POST /peliculas.json
  def create
    @pelicula = Pelicula.new(pelicula_params)

    respond_to do |format|
      if @pelicula.save
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully created.' }
        format.json { render :show, status: :created, location: @pelicula }
      else
        format.html { render :new }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peliculas/1
  # PATCH/PUT /peliculas/1.json
  def update
    respond_to do |format|
      if @pelicula.update(pelicula_params)
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully updated.' }
        format.json { render :show, status: :ok, location: @pelicula }
      else
        format.html { render :edit }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peliculas/1
  # DELETE /peliculas/1.json
  def destroy
    @pelicula.destroy
    respond_to do |format|
      format.html { redirect_to peliculas_url, notice: 'Pelicula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelicula
      @pelicula = Pelicula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pelicula_params
      params.require(:pelicula).permit(:cod_pel, :titulo, :ano, :categoria)
    end
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/views/peliculas/_form.html.erb
<%= form_for(@pelicula) do |f| %>
  <% if @pelicula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pelicula.errors.count, "error") %> prohibited this pelicula from being saved:</h2>

      <ul>
      <% @pelicula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod_pel %><br>
    <%= f.number_field :cod_pel %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.number_field :ano %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peliculas/edit.html.erb
<h1>Editing Pelicula</h1>

<%= render 'form' %>

<%= link_to 'Show', @pelicula %> |
<%= link_to 'Back', peliculas_path %>

app/views/peliculas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Peliculas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Cod pel</th>
      <th>Titulo</th>
      <th>Ano</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peliculas.each do |pelicula| %>
      <tr>
        <td><%= pelicula.cod_pel %></td>
        <td><%= pelicula.titulo %></td>
        <td><%= pelicula.ano %></td>
        <td><%= pelicula.categoria %></td>
        <td><%= link_to 'Show', pelicula %></td>
        <td><%= link_to 'Edit', edit_pelicula_path(pelicula) %></td>
        <td><%= link_to 'Destroy', pelicula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pelicula', new_pelicula_path %>

app/views/peliculas/new.html.erb
<h1>New Pelicula</h1>

<%= render 'form' %>

<%= link_to 'Back', peliculas_path %>

app/views/peliculas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cod pel:</strong>
  <%= @pelicula.cod_pel %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @pelicula.titulo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @pelicula.ano %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @pelicula.categoria %>
</p>

<%= link_to 'Edit', edit_pelicula_path(@pelicula) %> |
<%= link_to 'Back', peliculas_path %>